version: '3.4'

services:
  xttsapiserver:
    image: xttsapiserver
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: >
      bash -lc "python3 -m xtts_api_server --listen -p 8020
      -t 'http://localhost:8020'
      -sf '/xtts-server/speakers'
      -o '/xtts-server/output'
      -mf '/xtts-server/models'
      -ms api
      --deepspeed"
    ports:
      - "${HOST_PORT:-8020}:${CONTAINER_PORT:-8020}"
    volumes:
      - ../xtts-server:/xtts-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
